apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-translation-app
  title: Quarkus Translation Service
  description: Quarkus app that serves translations from JSON with Dev Spaces support
  tags:
    - quarkus
    - java
    - openshift
    - devfile
spec:
  owner: group:default/developers
  type: service

  parameters:
  - title: Workshop Configuration
    properties:
      general:
        type: object
        title: General Settings
        properties:
          gitlabOwner:
            title: GitLab Owner
            type: string
            default: self-provisioned
            description: GitLab group or username that owns the repository
            ui:widget: hidden
          gitlabRepository:
            title: GitLab Repository Name
            type: string
            default: workshop-repository
            description: Repository name used to initialize workshop

  steps:
    - id: fetch
      name: Fetch Base Repo
      action: fetch:template
      input:
        url: https://github.com/na-launch/mizho-workshop-module1
        targetPath: ./
        
    #################################
    ## Create Empty Repository
    #################################
    - id: publishEmptyRepo
      name: "Create Empty Repository"
      action: publish:gitlab
      input:
        description: |
          Self-Service Repository
        repoUrl: gitlab.com?owner=${{ parameters.general.gitlabOwner }}&repo=${{ parameters.general.gitlabRepository }}
        defaultBranch: main
        settings:
          visibility: "internal"
        branches:
          - name: main
            protect: true

    - id: publish
      name: Push to GitLab
      action: publish:gitlab
      input:
        repoUrl: gitlab.com?owner=${{ user.entity.metadata.name }}&repo=testing
        setUserAsOwner: false
        defaultBranch: main
        description: Quarkus Translation Service generated from RHDH
        visibility: public

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: View in Developer Hub
        icon: catalog
        entityRef: component:quarkus-translation-app
